### ISSUE TITLE
Project Proposal Feedback

### ISSUE THREAD

**Issue by PhilChodrow** [PengWu2626/PIC16B_GroupProject#4]
Hi Peng, Weixin, Miao, and Jiamu, 

This is a nice proposal! You've clearly thought about your problem, and I'm excited to see what you produce. 

I'd like you to be a little more specific about *how* you are going to create your app. Are you going to use Flask or another webapp framework? Or a classical graphical interface package like `tkinter`? It's ok to choose something different (and some of them are indeed easier), but I would like you to be specific about your plan here. It's ok to change your mind -- just describe what you're going to try first. 

I strongly recommend that you look into *transfer learning* when training your model. Transfer learning involves using a partially trained model from another setting, and then training it just a little bit more on your task. We'll actually do some transfer learning in [Blog Post 5](https://www.philchodrow.com/PIC16B//posts/blog-post-5), but probably should start doing some of your own research and study before we get there. 

Please revise to specify what app framework you plan to use, and then reply to this issue to let me know. I'll then reassess your proposal for credit. 

You've got this!

**Comment by PengWu2626** [comment]
> 
We will use Flask to build our webapp, then load up for our pre-trained model using `pickle.load()`. This webapp allows the user to upload dog images and show the prediction results.

**Comment by 99-j** [comment]
Hello Prof. Chodrow and teammates,
Thank you for your advice! I've updated the framework in the README file. #5 
@PhilChodrow @PengWu2626

**Comment by PhilChodrow** [comment]
Ok! Your revisions look good and you have received credit for this assignment. 

Flask is a good solution, but you might also find it rewarding to do a bit of research about possible alternatives.
